name: Deploy to BlueHost

on:
  push:
    branches: [ deploy ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, dom, fileinfo, mysql, curl
        tools: composer:v2

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.VPS_SSH_KEY }}
        known_hosts: 'temp'  # Required by action but we override below

    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh
        # Add server fingerprint (from GitHub Secrets)
        echo "${{ secrets.VPS_HOST }} ${{ secrets.SSH_FINGERPRINT }}" >> ~/.ssh/known_hosts
        # Verify fingerprint
        ssh-keygen -l -f ~/.ssh/known_hosts | grep "${{ secrets.VPS_HOST }}"

    - name: Sync Files
      run: |
        rsync -avz --delete \
          --exclude='.env' \
          --exclude='storage/*' \
          --exclude='vendor/' \
          -e "ssh -o StrictHostKeyChecking=yes" \
          ./ ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }}:${{ secrets.VPS_BACKEND_PATH }}

    - name: Remote Commands
      run: |
        ssh -o StrictHostKeyChecking=yes \
          ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} \
          "cd ${{ secrets.VPS_BACKEND_PATH }} && \
          composer install --no-dev --optimize-autoloader && \
          php artisan optimize:clear && \
          php artisan optimize && \
          chmod -R 755 storage bootstrap/cache"
