name: Deploy to BlueHost

on:
  push:
    branches: [deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # -----------------------------------
    # STEP 1: Prepare the environment
    # -----------------------------------
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, dom, fileinfo, mysql, curl 
        tools: composer:v2

    # -----------------------------------
    # STEP 2: SSH Setup
    # -----------------------------------
    - name: Configure SSH Environment
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t ecdsa ${{ secrets.VPS_HOST }} > ~/.ssh/known_hosts

    # -----------------------------------
    # STEP 3: Deployment
    # -----------------------------------
    - name: Install Dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Sync Files
      run: |
        rsync -avz --delete \
          --exclude='.env' \
          --exclude='storage/*' \
          --exclude='node_modules/' \
          -e "ssh -i ~/.ssh/id_rsa -o LogLevel=ERROR" \
          ./ ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }}:${{ secrets.VPS_BACKEND_PATH }}

   # -----------------------------------
    # STEP 4: Post-Deployment Commands
    # -----------------------------------
    - name: Execute Remote Commands
      run: |
        set +e
        ssh -i ~/.ssh/id_rsa \
          -o ConnectTimeout=30 \
          ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} \
          "cd ${{ secrets.VPS_BACKEND_PATH }} && \
          (/usr/local/bin/php artisan optimize:clear || echo 'Artisan clear failed') && \
          (/usr/local/bin/php artisan optimize || echo 'Artisan optimize failed') && \
          (chmod -R 755 storage bootstrap/cache || echo 'Chmod failed') && \
          echo '✓ Post-deployment steps attempted'"
        set -e

    # -----------------------------------
    # STEP 5: Verification
    # -----------------------------------
    - name: Verify Deployment
      run: |
        ssh -i ~/.ssh/id_rsa \
          ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} \
          "cd ${{ secrets.VPS_BACKEND_PATH }} && \
          /usr/local/bin/php artisan --version && \
          ls -la storage/framework/ && \
          echo '✓ Verification successful'" 
