name: Deploy to BlueHost

on:
  push:
    branches: [deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, dom, fileinfo, mysql, curl
        tools: composer:v2

    - name: Configure SSH Environment
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        
        # Get all host key types
        ssh-keyscan -t rsa,ecdsa,ed25519 ${{ secrets.VPS_HOST }} > ~/.ssh/known_hosts 
        chmod 644 ~/.ssh/known_hosts
        
        # Debug output
        echo "=== SSH Configuration ==="
        ls -la ~/.ssh
        echo "Known hosts:"
        cat ~/.ssh/known_hosts
        echo "Private key head:"
        head -n 3 ~/.ssh/id_rsa

    - name: Test SSH Connection (With Debug)
      run: |
        echo "=== Testing SSH Connection ==="
        ssh -vvv -o BatchMode=yes \
            -o StrictHostKeyChecking=yes \
            -i ~/.ssh/id_rsa \
            ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} \
            "echo 'SSH connection successful!'" || true

    - name: Rsync Deployment
      if: success()
      run: |
        rsync -avz --delete \
          --exclude='.env' \
          --exclude='storage/*' \
          --exclude='vendor/' \
          -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=yes" \
          ./ ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }}:${{ secrets.VPS_BACKEND_PATH }}

    - name: Run Remote Commands
      if: success()
      run: |
        ssh -i ~/.ssh/id_rsa \
          ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} \
          "cd ${{ secrets.VPS_BACKEND_PATH }} && \
          composer install --no-dev --optimize-autoloader && \
          php artisan optimize:clear && \
          php artisan optimize && \
          chmod -R 755 storage bootstrap/cache"
