name: Production Deployment

on:
  push:
    branches: [deploy]  # Change to your production branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Setup PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, json, tokenizer, openssl # Add any required extensions

      - name: Install dependencies
        run: |
          composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction
          composer dump-autoload --optimize

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Create remote directories
        run: |
          ssh -o StrictHostKeyChecking=no \
              ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} \
              "mkdir -p ${{ secrets.VPS_BACKEND_PATH }}/{storage/framework/views,storage/framework/cache,bootstrap/cache,storage/logs}"

      - name: Rsync application files
        run: |
          rsync -avz --delete \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='.env' \
            --exclude='node_modules' \
            --exclude='storage' \
            --exclude='tests' \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./ \
            ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }}:${{ secrets.VPS_BACKEND_PATH }}/

      - name: Set permissions
        run: |
          ssh -o StrictHostKeyChecking=no \
              ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} \
              "chmod -R 755 ${{ secrets.VPS_BACKEND_PATH }}/storage \
               && chmod -R 755 ${{ secrets.VPS_BACKEND_PATH }}/bootstrap/cache"

      - name: Run deployment commands
        run: |
          ssh -o StrictHostKeyChecking=no \
              ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} \
              "cd ${{ secrets.VPS_BACKEND_PATH }} && \
               php artisan config:clear && \
               php artisan view:clear && \
               php artisan cache:clear && \
               php artisan optimize && \
               php artisan storage:link"
