name: Deploy to BlueHost

on:
  push:
    branches: [deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, dom, fileinfo, mysql, curl
        tools: composer:v2

    - name: Configure SSH Environment
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 700 ~/.ssh
        chmod 600 ~/.ssh/id_rsa
        echo "${{ secrets.VPS_HOST }} ${{ secrets.SSH_FINGERPRINT }}" > ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts
        echo "Host bluehost" >> ~/.ssh/config
        echo "  HostName ${{ secrets.VPS_HOST }}" >> ~/.ssh/config
        echo "  User ${{ secrets.VPS_USERNAME }}" >> ~/.ssh/config
        echo "  IdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config
        echo "  IdentitiesOnly yes" >> ~/.ssh/config
        echo "  StrictHostKeyChecking yes" >> ~/.ssh/config

    - name: Verify SSH Connection
      run: |
        echo "Testing SSH connection..."
        ssh -vT ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} "echo 'SSH connection successful!'" || true
        echo "Debug info:"
        ls -la ~/.ssh
        cat ~/.ssh/config

    - name: Sync Files via Rsync
      run: |
        rsync -avz --delete \
          --exclude='.env' \
          --exclude='storage/*' \
          --exclude='vendor/' \
          -e "ssh -v -i ~/.ssh/id_rsa" \
          ./ ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }}:${{ secrets.VPS_BACKEND_PATH }}

    - name: Run Remote Commands
      run: |
        ssh -v -i ~/.ssh/id_rsa \
          ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} \
          "cd ${{ secrets.VPS_BACKEND_PATH }} && \
          composer install --no-dev --optimize-autoloader && \
          php artisan optimize:clear && \
          php artisan optimize && \
          chmod -R 755 storage bootstrap/cache"
